require("lshay.plugins-setup")
require("lshay.core.options")
require("lshay.core.keymaps")
require("lshay.core.colorscheme")
require("lshay.plugins.comment")
require("lshay.plugins.nvim-tree")
require("lshay.plugins.lualine")
require("lshay.plugins.telescope")
require("lshay.plugins.nvim-cmp")
require("lshay.plugins.lsp.mason")
require("lshay.plugins.lsp.lspsaga")
require("lshay.plugins.lsp.lspconfig")
require("lshay.plugins.lsp.null-ls")
require("lshay.plugins.autopairs")
require("lshay.plugins.treesitter")
require("lshay.plugins.gitsigns")
require("lshay.plugins.neo-tree")
require("lshay.plugins.bufferline")
require("lshay.core.globals")


-- require("lshay.plugins.vim-which-key")
